package com.venkatS3246961.hostelmanagment.activities

data class HostelData(
    val hostelname: String = "",
    val hostellocation: String = "",
    val hostelcontact: String = "",
    val hosteldescription: String = "",
    var featureList: List<FeaturesData> = emptyList(),
    val hostelimage: Int=0,
    val hostelimage1: Int=0,
    val hostelimage2: Int=0,
    val hostelimage3: Int=0,
    val hostelimage4: Int=0,
    val hostelimage5: Int=0,
    val hostelimage6: Int=0,
    val hostelimage7: Int=0,
    val hostelimage8: Int=0,
    val hostelimage9: Int=0,
    val hostelimage10: Int=0,
    val hostelimage11: Int=0,
    val hostelimage12: Int=0,
    val hostelimage13: Int=0,
    val boldtext1: String = "",
    val boldtext2: String = "",
    val boldtext22: String = "",
    val boldtext3: String = "",
    val boldtext4: String = "",
    val boldtext5: String = "",
    val boldtext6: String = "",
    val boldtext7: String = "",
    val boldtext8: String = "",
    val boldtext9: String = "",
    val boldtext10: String = "",
    val boldtext11: String = "",
    val boldtext12: String = "",
    val boldtext13: String = "",
    val normaltext1: String = "",
    val normaltext2: String = "",
    val normaltext3: String = "",
    val normaltext4: String = "",
    val normaltext5: String = "",
    val normaltext6: String = "",
    val normaltext7: String = "",
    val normaltext8: String = "",
    val normaltext9: String = "",
    val normaltext10: String = "",
    val normaltext11: String = "",
    val normaltext12: String = "",
    val normaltext13: String = "",
    val hostelprice: Int = 0,
    val hosteltype: String = "",
    val hostelfacilities: String = "",
    val hostelrating: String = "",
    val hostelreviews: String = "",
    val totalrooms: Int=0,
    val availablerooms: Int=0,

)
